### ISSUE TITLE
network view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#7] opened 2016-05-27 23:06 UTC
lets create a network view of proteins and kinases that interact with it. Size of protein correlates with number of mutations. Clicking on protein opens protein view. 

more visualisation ideas coming later.

**Comment by krassowski** [comment] 2016-06-06 19:59
I have a question about kinases from the file with sites. Some entries in "kinases" column are just names of proteins like `CHEK2`, `FYN`, `SRC`, but some are named like: `GRK_GROUP`, `PKG/CGK_GROUP`, `CAM-KII_GROUP`. How should I treat those groups?

For example if I have a `CDK_GROUP` (and many `CDK`* proteins already loaded) should I create an additional table 'group', and then show all proteins from referred group clustered together in the network view?

If so, where can I find an appropriate classification of kinase into groups? (I found http://kinase.com/web/current/kinbase/ useful for manual exploration, but I am not sure if we can incorporate those data into the framework. By the way, the groups are referred here as families).

**Comment by reimand0** [comment] 2016-06-07 03:10
Good point. Let’s keep these group nodes as kinases, except that they are labelled with a separate flag. These could show in the visualisation with a different shape or form. 

We might also consider mapping these to actual kinases in the group, but these mappings are usually subjective and caused by limitations of the experimental platform the researchers used.

**Comment by krassowski** [comment] 2016-06-20 16:42
This page should provide reasonable overview of the progress, without enormous loading time (as contrast to TP53) until I change the database or get a way to OICR's server: http://krassowski.pythonanywhere.com/network/show/BRCA1. We can use following properties to add more information to the plot: fill color of nodes, color of edges, thickness of edges and position of nodes. I think this would be a good topic to talk about later.

**Comment by reimand0** [comment] 2016-06-20 18:29
thanks, now it looks more reasonable. I think we can start by increasing
the canvas size. What are the current criteria for node size and color?

**Comment by krassowski** [comment] 2016-06-20 19:12
node size is calculated as following:
`radius = (base size) * (2 if the node is a group of kinases, else 1) + (mutations count bonus)`
where mutations count bonus is calculated as: `(logarithm of base 10 from count of mutations + 1) * some scaling factor` (adding one gives bonus equal to 0 when there are no mutations). In the actual code:

```javascript
var is_group = is_group ? 1 : 0

var r = config.minimalRadius
// the groups are shown as two times bigger
r *= (is_group + 1)
// more mutations = bigger circle
r += 6 * Math.log10(mutations_count + 1)
```
Of course the factors are arbitrary, just to have it not to small and not to big.

The color code for borders is:
 - blue: currently analyzed protein,
 - green: just a kinase,
 - red: kinases group.

**Comment by krassowski** [comment] 2016-06-23 23:21
Currently clicking on the circle of a kinase group leads to an undefined behavior (404). The easiest fix would be to stop executing any action on click on the group circle. But for the user who would expect uniform response throughout the nodes it might be beneficial to define another behavior. Although the mappings are usually subjective, maybe we can just assume that the nodes starting with the same names as groups should be grouped together by these groups? For example: in the network of TP53 the CDK group is reduntant when looking on all the CDK proteins available around. Would it be a nice additional feature to group them that way or it does not makes sense due to some biological or data-related issues?

**Comment by krassowski** [comment] 2016-06-25 12:37
As the discussion proceeded via emails and now we have the kinase families mappings, I have next question that I figured out when implementing the groupings in network.

If there are ALK7, CDK1, CDK2 and CDK_GROUP listed as kinases in a site description, what behavior would be suitable:
1. we have nodes ALK7, CDK[group] and within the group there are two subnodes: CDK1 and CDK2
2. we have nodes ALK7, CDK[group] and within the group there are all kinases belonging to CDK group, including the CDK1 and CDK2, but along with many others. CDK1 and CDK2 might be somehow indicated (by color for example) that they are 'confirmed twice'.

I think that both options (1 and 2) make some biological sense (someone confirmed that the CDK1 and CDK2 interacts with that specific site vs someone confirmed that all other kinases from this group might behave similarly and interact with the site) but I certainly need feedback with this one; is my reasoning correct?

**Comment by reimand0** [comment] 2016-06-27 23:00
Let's expand the network view to individual sites. 

This also has the advantage that we can somehow show the number of mutations in sites, for example by intensity of color. 

![img_0502](https://cloud.githubusercontent.com/assets/19268349/16398560/4b68d05e-3c99-11e6-9e36-db592b01c9cb.JPG)

**Comment by reimand0** [comment] 2016-08-12 16:11
For every site in the network, let's have all kinases as separate nodes. if one kinase X binds 5 sites, then 5 nodes of kinases X will be shown, one kinase for each site. When we move mouse over one kinase X, other 4 kinaseX nodes will also change color.

**Comment by reimand0** [comment] 2016-08-17 16:09
i like the network view but it is occasionally quite complex. One way to reduce complexity is to have sites at two orbits rather than one. 

for example, protein1 on 1st orbit, protein2 on 2nd orbit, protein3 on 1st orbit, protein4 on 2nd orbit, etc

**Comment by krassowski** [comment] 2016-11-05 18:13
The multiple orbit approach is implemented for quite long time. Could we close this issue?

**Closed** 2016-11-11 14:46 UTC
Labels: enhancement
